spring:
  application:
    name: yh-service-base-filesystem
  data:
    mongodb:
      database: file_system
      uri: mongodb://localhost:27017/
  servlet:
    multipart:
      enabled: true
      #最大支持文件大小
      max-file-size: 5MB
      #最大支持请求大小
      max-request-size: 30MB
server:
  port: 22100
yh:
  fastdfs:
    #tracker_servers: 172.16.26.45:22122,172.16.26.201:22122
    tracker_servers: 172.16.13.250:22122
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: utf-8
