server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///localhost
    username: root
    password: root
  resources:
    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
mybatis:
  #mapper路径地址和别名
  type-aliases-package: com.itfxp.bean
  mapper-locations: classpath:/mapper/*.xml